# Regression project

## 0. Load packages

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

%matplotlib inline

## 1. Read the data

In [2]:
# Read the data
data = pd.read_csv('data/bikeshare.csv')

In [3]:
data

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0000,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0000,8,32,40
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0000,5,27,32
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0000,3,10,13
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0000,0,1,1
5,2011-01-01 05:00:00,1,0,0,2,9.84,12.880,75,6.0032,0,1,1
6,2011-01-01 06:00:00,1,0,0,1,9.02,13.635,80,0.0000,2,0,2
7,2011-01-01 07:00:00,1,0,0,1,8.20,12.880,86,0.0000,1,2,3
8,2011-01-01 08:00:00,1,0,0,1,9.84,14.395,75,0.0000,1,7,8
9,2011-01-01 09:00:00,1,0,0,1,13.12,17.425,76,0.0000,8,6,14
10,2011-01-01 10:00:00,1,0,0,1,15.58,19.695,76,16.9979,12,24,36
11,2011-01-01 11:00:00,1,0,0,1,14.76,16.665,81,19.0012,26,30,56
12,2011-01-01 12:00:00,1,0,0,1,17.22,21.210,77,19.0012,29,55,84
13,2011-01-01 13:00:00,1,0,0,2,18.86,22.725,72,19.9995,47,47,94
14,2011-01-01 14:00:00,1,0,0,2,18.86,22.725,72,19.0012,35,71,106
15,2011-01-01 15:00:00,1,0,0,2,18.04,21.970,77,19.9995,40,70,110
16,2011-01-01 16:00:00,1,0,0,2,17.22,21.210,82,19.9995,41,52,93
17,2011-01-01 17:00:00,1,0,0,2,18.04,21.970,82,19.0012,15,52,67
18,2011-01-01 18:00:00,1,0,0,3,17.22,21.210,88,16.9979,9,26,35
19,2011-01-01 19:00:00,1,0,0,3,17.22,21.210,88,16.9979,6,31,37
20,2011-01-01 20:00:00,1,0,0,2,16.40,20.455,87,16.9979,11,25,36
21,2011-01-01 21:00:00,1,0,0,2,16.40,20.455,87,12.9980,3,31,34
22,2011-01-01 22:00:00,1,0,0,2,16.40,20.455,94,15.0013,11,17,28
23,2011-01-01 23:00:00,1,0,0,2,18.86,22.725,88,19.9995,15,24,39
24,2011-01-02 00:00:00,1,0,0,2,18.86,22.725,88,19.9995,4,13,17
25,2011-01-02 01:00:00,1,0,0,2,18.04,21.970,94,16.9979,1,16,17
26,2011-01-02 02:00:00,1,0,0,2,17.22,21.210,100,19.0012,1,8,9
27,2011-01-02 03:00:00,1,0,0,2,18.86,22.725,94,12.9980,2,4,6
28,2011-01-02 04:00:00,1,0,0,2,18.86,22.725,94,12.9980,2,1,3
29,2011-01-02 06:00:00,1,0,0,3,17.22,21.210,77,19.9995,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...
10856,2012-12-18 18:00:00,4,0,1,1,15.58,19.695,46,22.0028,13,512,525
10857,2012-12-18 19:00:00,4,0,1,1,15.58,19.695,46,26.0027,19,334,353
10858,2012-12-18 20:00:00,4,0,1,1,14.76,16.665,50,16.9979,4,264,268
10859,2012-12-18 21:00:00,4,0,1,1,14.76,17.425,50,15.0013,9,159,168
10860,2012-12-18 22:00:00,4,0,1,1,13.94,16.665,49,0.0000,5,127,132
10861,2012-12-18 23:00:00,4,0,1,1,13.94,17.425,49,6.0032,1,80,81
10862,2012-12-19 00:00:00,4,0,1,1,12.30,15.910,61,0.0000,6,35,41
10863,2012-12-19 01:00:00,4,0,1,1,12.30,15.910,65,6.0032,1,14,15
10864,2012-12-19 02:00:00,4,0,1,1,11.48,15.150,65,6.0032,1,2,3
10865,2012-12-19 03:00:00,4,0,1,1,10.66,13.635,75,8.9981,0,5,5
10866,2012-12-19 04:00:00,4,0,1,1,9.84,12.120,75,8.9981,1,6,7
10867,2012-12-19 05:00:00,4,0,1,1,10.66,14.395,75,6.0032,2,29,31
10868,2012-12-19 06:00:00,4,0,1,1,9.84,12.880,75,6.0032,3,109,112
10869,2012-12-19 07:00:00,4,0,1,1,10.66,13.635,75,8.9981,3,360,363
10870,2012-12-19 08:00:00,4,0,1,1,9.84,12.880,87,7.0015,13,665,678
10871,2012-12-19 09:00:00,4,0,1,1,11.48,14.395,75,7.0015,8,309,317
10872,2012-12-19 10:00:00,4,0,1,1,13.12,16.665,70,7.0015,17,147,164
10873,2012-12-19 11:00:00,4,0,1,1,16.40,20.455,54,15.0013,31,169,200
10874,2012-12-19 12:00:00,4,0,1,1,16.40,20.455,54,19.0012,33,203,236
10875,2012-12-19 13:00:00,4,0,1,1,17.22,21.210,50,12.9980,30,183,213
10876,2012-12-19 14:00:00,4,0,1,1,17.22,21.210,50,12.9980,33,185,218
10877,2012-12-19 15:00:00,4,0,1,1,17.22,21.210,50,19.0012,28,209,237
10878,2012-12-19 16:00:00,4,0,1,1,17.22,21.210,50,23.9994,37,297,334
10879,2012-12-19 17:00:00,4,0,1,1,16.40,20.455,50,26.0027,26,536,562
10880,2012-12-19 18:00:00,4,0,1,1,15.58,19.695,50,23.9994,23,546,569
10881,2012-12-19 19:00:00,4,0,1,1,15.58,19.695,50,26.0027,7,329,336
10882,2012-12-19 20:00:00,4,0,1,1,14.76,17.425,57,15.0013,10,231,241
10883,2012-12-19 21:00:00,4,0,1,1,13.94,15.910,61,15.0013,4,164,168
10884,2012-12-19 22:00:00,4,0,1,1,13.94,17.425,61,6.0032,12,117,129
10885,2012-12-19 23:00:00,4,0,1,1,13.12,16.665,66,8.9981,4,84,88

# 2. Data preprocessing

## 2.1. Handle a datetime variable

In [4]:
# Add 'year', 'month' and 'hour'
datetime = pd.DatetimeIndex(data['datetime'])
data['year'] = datetime.year
data['month'] = datetime.month
data['hour'] = datetime.hour

# Drop 'datetime'
data.drop('datetime', axis=1, inplace=True)

In [5]:
data

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count,year,month,hour
0,1,0,0,1,9.84,14.395,81,0.0000,3,13,16,2011,1,0
1,1,0,0,1,9.02,13.635,80,0.0000,8,32,40,2011,1,1
2,1,0,0,1,9.02,13.635,80,0.0000,5,27,32,2011,1,2
3,1,0,0,1,9.84,14.395,75,0.0000,3,10,13,2011,1,3
4,1,0,0,1,9.84,14.395,75,0.0000,0,1,1,2011,1,4
5,1,0,0,2,9.84,12.880,75,6.0032,0,1,1,2011,1,5
6,1,0,0,1,9.02,13.635,80,0.0000,2,0,2,2011,1,6
7,1,0,0,1,8.20,12.880,86,0.0000,1,2,3,2011,1,7
8,1,0,0,1,9.84,14.395,75,0.0000,1,7,8,2011,1,8
9,1,0,0,1,13.12,17.425,76,0.0000,8,6,14,2011,1,9
10,1,0,0,1,15.58,19.695,76,16.9979,12,24,36,2011,1,10
11,1,0,0,1,14.76,16.665,81,19.0012,26,30,56,2011,1,11
12,1,0,0,1,17.22,21.210,77,19.0012,29,55,84,2011,1,12
13,1,0,0,2,18.86,22.725,72,19.9995,47,47,94,2011,1,13
14,1,0,0,2,18.86,22.725,72,19.0012,35,71,106,2011,1,14
15,1,0,0,2,18.04,21.970,77,19.9995,40,70,110,2011,1,15
16,1,0,0,2,17.22,21.210,82,19.9995,41,52,93,2011,1,16
17,1,0,0,2,18.04,21.970,82,19.0012,15,52,67,2011,1,17
18,1,0,0,3,17.22,21.210,88,16.9979,9,26,35,2011,1,18
19,1,0,0,3,17.22,21.210,88,16.9979,6,31,37,2011,1,19
20,1,0,0,2,16.40,20.455,87,16.9979,11,25,36,2011,1,20
21,1,0,0,2,16.40,20.455,87,12.9980,3,31,34,2011,1,21
22,1,0,0,2,16.40,20.455,94,15.0013,11,17,28,2011,1,22
23,1,0,0,2,18.86,22.725,88,19.9995,15,24,39,2011,1,23
24,1,0,0,2,18.86,22.725,88,19.9995,4,13,17,2011,1,0
25,1,0,0,2,18.04,21.970,94,16.9979,1,16,17,2011,1,1
26,1,0,0,2,17.22,21.210,100,19.0012,1,8,9,2011,1,2
27,1,0,0,2,18.86,22.725,94,12.9980,2,4,6,2011,1,3
28,1,0,0,2,18.86,22.725,94,12.9980,2,1,3,2011,1,4
29,1,0,0,3,17.22,21.210,77,19.9995,0,2,2,2011,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10856,4,0,1,1,15.58,19.695,46,22.0028,13,512,525,2012,12,18
10857,4,0,1,1,15.58,19.695,46,26.0027,19,334,353,2012,12,19
10858,4,0,1,1,14.76,16.665,50,16.9979,4,264,268,2012,12,20
10859,4,0,1,1,14.76,17.425,50,15.0013,9,159,168,2012,12,21
10860,4,0,1,1,13.94,16.665,49,0.0000,5,127,132,2012,12,22
10861,4,0,1,1,13.94,17.425,49,6.0032,1,80,81,2012,12,23
10862,4,0,1,1,12.30,15.910,61,0.0000,6,35,41,2012,12,0
10863,4,0,1,1,12.30,15.910,65,6.0032,1,14,15,2012,12,1
10864,4,0,1,1,11.48,15.150,65,6.0032,1,2,3,2012,12,2
10865,4,0,1,1,10.66,13.635,75,8.9981,0,5,5,2012,12,3
10866,4,0,1,1,9.84,12.120,75,8.9981,1,6,7,2012,12,4
10867,4,0,1,1,10.66,14.395,75,6.0032,2,29,31,2012,12,5
10868,4,0,1,1,9.84,12.880,75,6.0032,3,109,112,2012,12,6
10869,4,0,1,1,10.66,13.635,75,8.9981,3,360,363,2012,12,7
10870,4,0,1,1,9.84,12.880,87,7.0015,13,665,678,2012,12,8
10871,4,0,1,1,11.48,14.395,75,7.0015,8,309,317,2012,12,9
10872,4,0,1,1,13.12,16.665,70,7.0015,17,147,164,2012,12,10
10873,4,0,1,1,16.40,20.455,54,15.0013,31,169,200,2012,12,11
10874,4,0,1,1,16.40,20.455,54,19.0012,33,203,236,2012,12,12
10875,4,0,1,1,17.22,21.210,50,12.9980,30,183,213,2012,12,13
10876,4,0,1,1,17.22,21.210,50,12.9980,33,185,218,2012,12,14
10877,4,0,1,1,17.22,21.210,50,19.0012,28,209,237,2012,12,15
10878,4,0,1,1,17.22,21.210,50,23.9994,37,297,334,2012,12,16
10879,4,0,1,1,16.40,20.455,50,26.0027,26,536,562,2012,12,17
10880,4,0,1,1,15.58,19.695,50,23.9994,23,546,569,2012,12,18
10881,4,0,1,1,15.58,19.695,50,26.0027,7,329,336,2012,12,19
10882,4,0,1,1,14.76,17.425,57,15.0013,10,231,241,2012,12,20
10883,4,0,1,1,13.94,15.910,61,15.0013,4,164,168,2012,12,21
10884,4,0,1,1,13.94,17.425,61,6.0032,12,117,129,2012,12,22
10885,4,0,1,1,13.12,16.665,66,8.9981,4,84,88,2012,12,23

## 2.2. Rename the variable 'count'

In [6]:
# "count" is a method, so it's best to name that column something else
data.rename(columns={'count':'total'}, inplace=True)

In [7]:
data

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,total,year,month,hour
0,1,0,0,1,9.84,14.395,81,0.0000,3,13,16,2011,1,0
1,1,0,0,1,9.02,13.635,80,0.0000,8,32,40,2011,1,1
2,1,0,0,1,9.02,13.635,80,0.0000,5,27,32,2011,1,2
3,1,0,0,1,9.84,14.395,75,0.0000,3,10,13,2011,1,3
4,1,0,0,1,9.84,14.395,75,0.0000,0,1,1,2011,1,4
5,1,0,0,2,9.84,12.880,75,6.0032,0,1,1,2011,1,5
6,1,0,0,1,9.02,13.635,80,0.0000,2,0,2,2011,1,6
7,1,0,0,1,8.20,12.880,86,0.0000,1,2,3,2011,1,7
8,1,0,0,1,9.84,14.395,75,0.0000,1,7,8,2011,1,8
9,1,0,0,1,13.12,17.425,76,0.0000,8,6,14,2011,1,9
10,1,0,0,1,15.58,19.695,76,16.9979,12,24,36,2011,1,10
11,1,0,0,1,14.76,16.665,81,19.0012,26,30,56,2011,1,11
12,1,0,0,1,17.22,21.210,77,19.0012,29,55,84,2011,1,12
13,1,0,0,2,18.86,22.725,72,19.9995,47,47,94,2011,1,13
14,1,0,0,2,18.86,22.725,72,19.0012,35,71,106,2011,1,14
15,1,0,0,2,18.04,21.970,77,19.9995,40,70,110,2011,1,15
16,1,0,0,2,17.22,21.210,82,19.9995,41,52,93,2011,1,16
17,1,0,0,2,18.04,21.970,82,19.0012,15,52,67,2011,1,17
18,1,0,0,3,17.22,21.210,88,16.9979,9,26,35,2011,1,18
19,1,0,0,3,17.22,21.210,88,16.9979,6,31,37,2011,1,19
20,1,0,0,2,16.40,20.455,87,16.9979,11,25,36,2011,1,20
21,1,0,0,2,16.40,20.455,87,12.9980,3,31,34,2011,1,21
22,1,0,0,2,16.40,20.455,94,15.0013,11,17,28,2011,1,22
23,1,0,0,2,18.86,22.725,88,19.9995,15,24,39,2011,1,23
24,1,0,0,2,18.86,22.725,88,19.9995,4,13,17,2011,1,0
25,1,0,0,2,18.04,21.970,94,16.9979,1,16,17,2011,1,1
26,1,0,0,2,17.22,21.210,100,19.0012,1,8,9,2011,1,2
27,1,0,0,2,18.86,22.725,94,12.9980,2,4,6,2011,1,3
28,1,0,0,2,18.86,22.725,94,12.9980,2,1,3,2011,1,4
29,1,0,0,3,17.22,21.210,77,19.9995,0,2,2,2011,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10856,4,0,1,1,15.58,19.695,46,22.0028,13,512,525,2012,12,18
10857,4,0,1,1,15.58,19.695,46,26.0027,19,334,353,2012,12,19
10858,4,0,1,1,14.76,16.665,50,16.9979,4,264,268,2012,12,20
10859,4,0,1,1,14.76,17.425,50,15.0013,9,159,168,2012,12,21
10860,4,0,1,1,13.94,16.665,49,0.0000,5,127,132,2012,12,22
10861,4,0,1,1,13.94,17.425,49,6.0032,1,80,81,2012,12,23
10862,4,0,1,1,12.30,15.910,61,0.0000,6,35,41,2012,12,0
10863,4,0,1,1,12.30,15.910,65,6.0032,1,14,15,2012,12,1
10864,4,0,1,1,11.48,15.150,65,6.0032,1,2,3,2012,12,2
10865,4,0,1,1,10.66,13.635,75,8.9981,0,5,5,2012,12,3
10866,4,0,1,1,9.84,12.120,75,8.9981,1,6,7,2012,12,4
10867,4,0,1,1,10.66,14.395,75,6.0032,2,29,31,2012,12,5
10868,4,0,1,1,9.84,12.880,75,6.0032,3,109,112,2012,12,6
10869,4,0,1,1,10.66,13.635,75,8.9981,3,360,363,2012,12,7
10870,4,0,1,1,9.84,12.880,87,7.0015,13,665,678,2012,12,8
10871,4,0,1,1,11.48,14.395,75,7.0015,8,309,317,2012,12,9
10872,4,0,1,1,13.12,16.665,70,7.0015,17,147,164,2012,12,10
10873,4,0,1,1,16.40,20.455,54,15.0013,31,169,200,2012,12,11
10874,4,0,1,1,16.40,20.455,54,19.0012,33,203,236,2012,12,12
10875,4,0,1,1,17.22,21.210,50,12.9980,30,183,213,2012,12,13
10876,4,0,1,1,17.22,21.210,50,12.9980,33,185,218,2012,12,14
10877,4,0,1,1,17.22,21.210,50,19.0012,28,209,237,2012,12,15
10878,4,0,1,1,17.22,21.210,50,23.9994,37,297,334,2012,12,16
10879,4,0,1,1,16.40,20.455,50,26.0027,26,536,562,2012,12,17
10880,4,0,1,1,15.58,19.695,50,23.9994,23,546,569,2012,12,18
10881,4,0,1,1,15.58,19.695,50,26.0027,7,329,336,2012,12,19
10882,4,0,1,1,14.76,17.425,57,15.0013,10,231,241,2012,12,20
10883,4,0,1,1,13.94,15.910,61,15.0013,4,164,168,2012,12,21
10884,4,0,1,1,13.94,17.425,61,6.0032,12,117,129,2012,12,22
10885,4,0,1,1,13.12,16.665,66,8.9981,4,84,88,2012,12,23

## 2.3. Drop the variables named 'casual' and 'registered'

In [8]:
data.drop(['casual', 'registered'], axis=1, inplace=True)

In [9]:
data

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,total,year,month,hour
0,1,0,0,1,9.84,14.395,81,0.0000,16,2011,1,0
1,1,0,0,1,9.02,13.635,80,0.0000,40,2011,1,1
2,1,0,0,1,9.02,13.635,80,0.0000,32,2011,1,2
3,1,0,0,1,9.84,14.395,75,0.0000,13,2011,1,3
4,1,0,0,1,9.84,14.395,75,0.0000,1,2011,1,4
5,1,0,0,2,9.84,12.880,75,6.0032,1,2011,1,5
6,1,0,0,1,9.02,13.635,80,0.0000,2,2011,1,6
7,1,0,0,1,8.20,12.880,86,0.0000,3,2011,1,7
8,1,0,0,1,9.84,14.395,75,0.0000,8,2011,1,8
9,1,0,0,1,13.12,17.425,76,0.0000,14,2011,1,9
10,1,0,0,1,15.58,19.695,76,16.9979,36,2011,1,10
11,1,0,0,1,14.76,16.665,81,19.0012,56,2011,1,11
12,1,0,0,1,17.22,21.210,77,19.0012,84,2011,1,12
13,1,0,0,2,18.86,22.725,72,19.9995,94,2011,1,13
14,1,0,0,2,18.86,22.725,72,19.0012,106,2011,1,14
15,1,0,0,2,18.04,21.970,77,19.9995,110,2011,1,15
16,1,0,0,2,17.22,21.210,82,19.9995,93,2011,1,16
17,1,0,0,2,18.04,21.970,82,19.0012,67,2011,1,17
18,1,0,0,3,17.22,21.210,88,16.9979,35,2011,1,18
19,1,0,0,3,17.22,21.210,88,16.9979,37,2011,1,19
20,1,0,0,2,16.40,20.455,87,16.9979,36,2011,1,20
21,1,0,0,2,16.40,20.455,87,12.9980,34,2011,1,21
22,1,0,0,2,16.40,20.455,94,15.0013,28,2011,1,22
23,1,0,0,2,18.86,22.725,88,19.9995,39,2011,1,23
24,1,0,0,2,18.86,22.725,88,19.9995,17,2011,1,0
25,1,0,0,2,18.04,21.970,94,16.9979,17,2011,1,1
26,1,0,0,2,17.22,21.210,100,19.0012,9,2011,1,2
27,1,0,0,2,18.86,22.725,94,12.9980,6,2011,1,3
28,1,0,0,2,18.86,22.725,94,12.9980,3,2011,1,4
29,1,0,0,3,17.22,21.210,77,19.9995,2,2011,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...
10856,4,0,1,1,15.58,19.695,46,22.0028,525,2012,12,18
10857,4,0,1,1,15.58,19.695,46,26.0027,353,2012,12,19
10858,4,0,1,1,14.76,16.665,50,16.9979,268,2012,12,20
10859,4,0,1,1,14.76,17.425,50,15.0013,168,2012,12,21
10860,4,0,1,1,13.94,16.665,49,0.0000,132,2012,12,22
10861,4,0,1,1,13.94,17.425,49,6.0032,81,2012,12,23
10862,4,0,1,1,12.30,15.910,61,0.0000,41,2012,12,0
10863,4,0,1,1,12.30,15.910,65,6.0032,15,2012,12,1
10864,4,0,1,1,11.48,15.150,65,6.0032,3,2012,12,2
10865,4,0,1,1,10.66,13.635,75,8.9981,5,2012,12,3
10866,4,0,1,1,9.84,12.120,75,8.9981,7,2012,12,4
10867,4,0,1,1,10.66,14.395,75,6.0032,31,2012,12,5
10868,4,0,1,1,9.84,12.880,75,6.0032,112,2012,12,6
10869,4,0,1,1,10.66,13.635,75,8.9981,363,2012,12,7
10870,4,0,1,1,9.84,12.880,87,7.0015,678,2012,12,8
10871,4,0,1,1,11.48,14.395,75,7.0015,317,2012,12,9
10872,4,0,1,1,13.12,16.665,70,7.0015,164,2012,12,10
10873,4,0,1,1,16.40,20.455,54,15.0013,200,2012,12,11
10874,4,0,1,1,16.40,20.455,54,19.0012,236,2012,12,12
10875,4,0,1,1,17.22,21.210,50,12.9980,213,2012,12,13
10876,4,0,1,1,17.22,21.210,50,12.9980,218,2012,12,14
10877,4,0,1,1,17.22,21.210,50,19.0012,237,2012,12,15
10878,4,0,1,1,17.22,21.210,50,23.9994,334,2012,12,16
10879,4,0,1,1,16.40,20.455,50,26.0027,562,2012,12,17
10880,4,0,1,1,15.58,19.695,50,23.9994,569,2012,12,18
10881,4,0,1,1,15.58,19.695,50,26.0027,336,2012,12,19
10882,4,0,1,1,14.76,17.425,57,15.0013,241,2012,12,20
10883,4,0,1,1,13.94,15.910,61,15.0013,168,2012,12,21
10884,4,0,1,1,13.94,17.425,61,6.0032,129,2012,12,22
10885,4,0,1,1,13.12,16.665,66,8.9981,88,2012,12,23

## 2.4. Add dummy variables

In [10]:
# Handling 'season' variable
season_dummies = pd.get_dummies(data.season, prefix='season')
season_dummies.drop(season_dummies.columns[0], axis=1, inplace=True)
data = pd.concat([data, season_dummies], axis=1)

data.drop('season', axis=1, inplace=True)

In [11]:
# # Handling 'hour' variable
# hour_dummies = pd.get_dummies(data.hour, prefix='hour')
# hour_dummies.drop(hour_dummies.columns[0], axis=1, inplace=True)
# data = pd.concat([data, hour_dummies], axis=1)

# data.drop('hour', axis=1, inplace=True)

In [12]:
data

,holiday,workingday,weather,temp,atemp,humidity,windspeed,total,year,month,hour,season_2,season_3,season_4
0,0,0,1,9.84,14.395,81,0.0000,16,2011,1,0,0,0,0
1,0,0,1,9.02,13.635,80,0.0000,40,2011,1,1,0,0,0
2,0,0,1,9.02,13.635,80,0.0000,32,2011,1,2,0,0,0
3,0,0,1,9.84,14.395,75,0.0000,13,2011,1,3,0,0,0
4,0,0,1,9.84,14.395,75,0.0000,1,2011,1,4,0,0,0
5,0,0,2,9.84,12.880,75,6.0032,1,2011,1,5,0,0,0
6,0,0,1,9.02,13.635,80,0.0000,2,2011,1,6,0,0,0
7,0,0,1,8.20,12.880,86,0.0000,3,2011,1,7,0,0,0
8,0,0,1,9.84,14.395,75,0.0000,8,2011,1,8,0,0,0
9,0,0,1,13.12,17.425,76,0.0000,14,2011,1,9,0,0,0
10,0,0,1,15.58,19.695,76,16.9979,36,2011,1,10,0,0,0
11,0,0,1,14.76,16.665,81,19.0012,56,2011,1,11,0,0,0
12,0,0,1,17.22,21.210,77,19.0012,84,2011,1,12,0,0,0
13,0,0,2,18.86,22.725,72,19.9995,94,2011,1,13,0,0,0
14,0,0,2,18.86,22.725,72,19.0012,106,2011,1,14,0,0,0
15,0,0,2,18.04,21.970,77,19.9995,110,2011,1,15,0,0,0
16,0,0,2,17.22,21.210,82,19.9995,93,2011,1,16,0,0,0
17,0,0,2,18.04,21.970,82,19.0012,67,2011,1,17,0,0,0
18,0,0,3,17.22,21.210,88,16.9979,35,2011,1,18,0,0,0
19,0,0,3,17.22,21.210,88,16.9979,37,2011,1,19,0,0,0
20,0,0,2,16.40,20.455,87,16.9979,36,2011,1,20,0,0,0
21,0,0,2,16.40,20.455,87,12.9980,34,2011,1,21,0,0,0
22,0,0,2,16.40,20.455,94,15.0013,28,2011,1,22,0,0,0
23,0,0,2,18.86,22.725,88,19.9995,39,2011,1,23,0,0,0
24,0,0,2,18.86,22.725,88,19.9995,17,2011,1,0,0,0,0
25,0,0,2,18.04,21.970,94,16.9979,17,2011,1,1,0,0,0
26,0,0,2,17.22,21.210,100,19.0012,9,2011,1,2,0,0,0
27,0,0,2,18.86,22.725,94,12.9980,6,2011,1,3,0,0,0
28,0,0,2,18.86,22.725,94,12.9980,3,2011,1,4,0,0,0
29,0,0,3,17.22,21.210,77,19.9995,2,2011,1,6,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10856,0,1,1,15.58,19.695,46,22.0028,525,2012,12,18,0,0,1
10857,0,1,1,15.58,19.695,46,26.0027,353,2012,12,19,0,0,1
10858,0,1,1,14.76,16.665,50,16.9979,268,2012,12,20,0,0,1
10859,0,1,1,14.76,17.425,50,15.0013,168,2012,12,21,0,0,1
10860,0,1,1,13.94,16.665,49,0.0000,132,2012,12,22,0,0,1
10861,0,1,1,13.94,17.425,49,6.0032,81,2012,12,23,0,0,1
10862,0,1,1,12.30,15.910,61,0.0000,41,2012,12,0,0,0,1
10863,0,1,1,12.30,15.910,65,6.0032,15,2012,12,1,0,0,1
10864,0,1,1,11.48,15.150,65,6.0032,3,2012,12,2,0,0,1
10865,0,1,1,10.66,13.635,75,8.9981,5,2012,12,3,0,0,1
10866,0,1,1,9.84,12.120,75,8.9981,7,2012,12,4,0,0,1
10867,0,1,1,10.66,14.395,75,6.0032,31,2012,12,5,0,0,1
10868,0,1,1,9.84,12.880,75,6.0032,112,2012,12,6,0,0,1
10869,0,1,1,10.66,13.635,75,8.9981,363,2012,12,7,0,0,1
10870,0,1,1,9.84,12.880,87,7.0015,678,2012,12,8,0,0,1
10871,0,1,1,11.48,14.395,75,7.0015,317,2012,12,9,0,0,1
10872,0,1,1,13.12,16.665,70,7.0015,164,2012,12,10,0,0,1
10873,0,1,1,16.40,20.455,54,15.0013,200,2012,12,11,0,0,1
10874,0,1,1,16.40,20.455,54,19.0012,236,2012,12,12,0,0,1
10875,0,1,1,17.22,21.210,50,12.9980,213,2012,12,13,0,0,1
10876,0,1,1,17.22,21.210,50,12.9980,218,2012,12,14,0,0,1
10877,0,1,1,17.22,21.210,50,19.0012,237,2012,12,15,0,0,1
10878,0,1,1,17.22,21.210,50,23.9994,334,2012,12,16,0,0,1
10879,0,1,1,16.40,20.455,50,26.0027,562,2012,12,17,0,0,1
10880,0,1,1,15.58,19.695,50,23.9994,569,2012,12,18,0,0,1
10881,0,1,1,15.58,19.695,50,26.0027,336,2012,12,19,0,0,1
10882,0,1,1,14.76,17.425,57,15.0013,241,2012,12,20,0,0,1
10883,0,1,1,13.94,15.910,61,15.0013,168,2012,12,21,0,0,1
10884,0,1,1,13.94,17.425,61,6.0032,129,2012,12,22,0,0,1
10885,0,1,1,13.12,16.665,66,8.9981,88,2012,12,23,0,0,1

In [13]:
print(data.columns)

Index(['holiday', 'workingday', 'weather', 'temp', 'atemp', 'humidity',
       'windspeed', 'total', 'year', 'month', 'hour', 'season_2', 'season_3',
       'season_4'],
      dtype='object')

## 2.5. Data save
- pickle
- csv

In [57]:
# pickle - version 1
data.to_pickle('data/processed_data.pkl')

In [59]:
# pickle - version 2
import pickle
with open('data/processed_data_v2.pkl', 'wb') as file:
    pickle.dump(data, file)

In [58]:
# csv
data.to_csv('data/processed_data.csv')

## 2.6. Data preparation

In [14]:
X = data.drop('total', axis=1)
Y = data['total']

In [15]:
X.head(5)

,holiday,workingday,weather,temp,atemp,humidity,windspeed,year,month,hour,season_2,season_3,season_4
0,0,0,1,9.84,14.395,81,0.0,2011,1,0,0,0,0
1,0,0,1,9.02,13.635,80,0.0,2011,1,1,0,0,0
2,0,0,1,9.02,13.635,80,0.0,2011,1,2,0,0,0
3,0,0,1,9.84,14.395,75,0.0,2011,1,3,0,0,0
4,0,0,1,9.84,14.395,75,0.0,2011,1,4,0,0,0

In [16]:
Y.head(5)

0    16
1    40
2    32
3    13
4     1
Name: total, dtype: int64

In [17]:
# Divide data into training set and test set
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=1234)

# 3. Train and validate models

Regression models in `sklearn`
- `sklearn.linear_model.Ridge`: [link](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Ridge.html)
- `sklearn.linear_model.Lasso`: [link](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html)
- `sklearn.linear_model.ElasticNet`: [link](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.ElasticNet.html#sklearn.linear_model.ElasticNet)
- `sklearn.linear_model.HuberRegressor`: [link](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.HuberRegressor.html#sklearn.linear_model.HuberRegressor)
- `sklearn.linear_model.PassiveAggressiveRegressor`: [link](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.PassiveAggressiveRegressor.html#sklearn.linear_model.PassiveAggressiveRegressor)
- `sklearn.tree.DecisionTreeRegressor`: [link](http://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html#sklearn.tree.DecisionTreeRegressor))
- `sklearn.tree.ExtraTreeRegressor`: [link](http://scikit-learn.org/stable/modules/generated/sklearn.tree.ExtraTreeRegressor.html#sklearn.tree.ExtraTreeRegressor)
- `sklearn.ensemble.RandomForestRegressor`: [link](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html#sklearn.ensemble.RandomForestRegressor)
- `sklearn.neighbors.KNeighborsRegressor`: [link](http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html#sklearn.neighbors.KNeighborsRegressor)
- `sklearn.kernel_ridge.KernelRidge`: [link](http://scikit-learn.org/stable/modules/generated/sklearn.kernel_ridge.KernelRidge.html#sklearn.kernel_ridge.KernelRidge)
- `sklearn.gaussian_process.GaussianProcessRegressor`: [link](http://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html#sklearn.gaussian_process.GaussianProcessRegressor)
- `sklearn.neural_network.MLPRegressor`: [link](http://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPRegressor.html#sklearn.neural_network.MLPRegressor)
- `sklearn.svm.SVR`: [link](http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html#sklearn.svm.SVR)
- `sklearn.svm.NuSVR`: [link](http://scikit-learn.org/stable/modules/generated/sklearn.svm.NuSVR.html#sklearn.svm.NuSVR)

## 3.1. Declare the models and parameter sets

In [18]:
## Import models

from sklearn.linear_model import Ridge, Lasso, ElasticNet, HuberRegressor
# from sklearn.linear_model import PassiveAggressiveRegressor, RANSACRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.kernel_ridge import KernelRidge
# from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.svm import SVR
# from sklear.svm import NuSVR

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [19]:
## Pre-allocate models and corresponding parameter candidates
models = []
params = []

In [20]:
model = ('Ridge', Ridge())
param = {
    'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0]
}

models.append(model)
params.append(param)

In [21]:
model = ('Lasso', Lasso())
param = {
    'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0]
}

models.append(model)
params.append(param)

In [22]:
model = ('ElasticNet', ElasticNet())
param = {
    'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0],
    'l1_ratio': [0.3, 0.5, 0.7]
}

models.append(model)
params.append(param)

In [23]:
model = ('HuberReg', HuberRegressor())
param = {
    'alpha': [0.0001, 0.001, 0.01]
}

models.append(model)
params.append(param)

In [24]:
model = ('CART', DecisionTreeRegressor())
param = {
    'max_depth': [2, 3, 4, 5],
    'min_samples_split': [0.02, 0.05]
}

models.append(model)
params.append(param)

In [25]:
model = ('RandomForest', RandomForestRegressor())
param = {
    'n_estimators': [50, 60, 70, 80, 90, 100],
    'max_features': [6, 7, 8, 9, 10]
}

models.append(model)
params.append(param)

In [26]:
model = ('StandardizedKNN', Pipeline([('Standardization', StandardScaler()), ('KNN', KNeighborsRegressor())]))
param = {
    'KNN__n_neighbors': [5, 10, 15, 20, 25, 30],
    'KNN__weights': ['uniform', 'distance']
}

models.append(model)
params.append(param)

In [27]:
model = ('KernelRidge', KernelRidge())
param = [
    {'kernel': ['linear'], 'alpha': [0.01, 0.05, 0.1, 0.5, 1.0]},
    {'kernel': ['rbf'], 'alpha': [0.01, 0.05, 0.1, 0.5, 1.0], 'gamma': [0.01, 0.05, 0.1, 0.5, 1.0, 5.0, 10.0]}
]

models.append(model)
params.append(param)

In [28]:
model = ('MLP', MLPRegressor())
param = {
    'hidden_layer_sizes': [(50, ), (100, ), (50, 50), (100, 100)],
    'solver': ['lbfgs'],
    'alpha': [0.0001, 0.001, 0.005],
    'max_iter': [200, 300, 400]
}

models.append(model)
params.append(param)

In [29]:
model = ('SVR', SVR())
param = [
    {'kernel': ['linear'], 'C': [1.0, 10.0, 50.0, 100.0]},
    {'kernel': ['rbf'], 'C': [1.0, 10.0, 50.0, 100.0], 'gamma': [0.01, 0.05, 0.1, 0.5, 1.0]},
    {'kernel': ['poly'], 'C': [1.0, 10.0, 50.0, 100.0], 'degree': [3, 4, 5]}
]

models.append(model)
params.append(param)

In [30]:
from pprint import pprint
pprint(models)
print("=" * 60)
pprint(params)

[('Ridge',
  Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)),
 ('Lasso',
  Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)),
 ('ElasticNet',
  ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)),
 ('HuberReg',
  HuberRegressor(alpha=0.0001, epsilon=1.35, fit_intercept=True, max_iter=100,
        tol=1e-05, warm_start=False)),
 ('CART',
  DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_split=1e-07,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, presort=False, random_state=None,
           splitter='best')),
 ('RandomForest',
  RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)),
 ('StandardizedKNN',
  Pipeline(steps=[('Standardization', StandardScaler(copy=True, with_mean=True, with_std=True)), ('KNN', KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='uniform'))])),
 ('KernelRidge',
  KernelRidge(alpha=1, coef0=1, degree=3, gamma=None, kernel='linear',
      kernel_params=None)),
 ('MLP',
  MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)),
 ('SVR',
  SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False))]
============================================================
[{'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0]},
 {'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0]},
 {'alpha': [0.1, 0.3, 0.5, 1.0, 3.0, 5.0, 10.0], 'l1_ratio': [0.3, 0.5, 0.7]},
 {'alpha': [0.0001, 0.001, 0.01]},
 {'max_depth': [2, 3, 4, 5], 'min_samples_split': [0.02, 0.05]},
 {'max_features': [6, 7, 8, 9, 10], 'n_estimators': [50, 60, 70, 80, 90, 100]},
 {'KNN__n_neighbors': [5, 10, 15, 20, 25, 30],
  'KNN__weights': ['uniform', 'distance']},
 [{'alpha': [0.01, 0.05, 0.1, 0.5, 1.0], 'kernel': ['linear']},
  {'alpha': [0.01, 0.05, 0.1, 0.5, 1.0],
   'gamma': [0.01, 0.05, 0.1, 0.5, 1.0, 5.0, 10.0],
   'kernel': ['rbf']}],
 {'alpha': [0.0001, 0.001, 0.005],
  'hidden_layer_sizes': [(50,), (100,), (50, 50), (100, 100)],
  'max_iter': [200, 300, 400],
  'solver': ['lbfgs']},
 [{'C': [1.0, 10.0, 50.0, 100.0], 'kernel': ['linear']},
  {'C': [1.0, 10.0, 50.0, 100.0],
   'gamma': [0.01, 0.05, 0.1, 0.5, 1.0],
   'kernel': ['rbf']},
  {'C': [1.0, 10.0, 50.0, 100.0], 'degree': [3, 4, 5], 'kernel': ['poly']}]]

## 3.2. Grid search with k-fold cross-validation

In [49]:
from sklearn.model_selection import KFold, GridSearchCV
from sklearn import metrics
from datetime import datetime

In [32]:
def gridsearch_cv_for_regression(model, param, kfold, train_input, train_target, scoring='neg_mean_squared_error', n_jobs=-1, tracking=True):
    '''
    [Parameters]
    - model: A tuple like ('name', MODEL)
    - param
    - scoring: neg_mean_absolute_error, neg_mean_squared_error, neg_median_absolute_error, r2
               (http://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter)
    - n_jobs: default as -1 (if it is -1, all CPU cores are used to train and validate models)
    - tracking: whether trained model's name and duration time are printed
    '''
    
    name = model[0]
    estimator = model[1]
    if tracking:
        start_time = datetime.now()
        print("[%s] Start parameter search for model '%s'" % (start_time, name))
        gridsearch = GridSearchCV(estimator=estimator, param_grid=param, cv=kfold, scoring=scoring, n_jobs=n_jobs)
        gridsearch.fit(train_input, train_target)
        end_time = datetime.now()
        duration_time = (end_time - start_time).seconds
        print("[%s] Finish parameter search for model '%s' (time: %d seconds)" % (end_time, name, duration_time))
        print()
    else:
        gridsearch = GridSearchCV(estimator=estimator, param_grid=param, cv=kfold, scoring=scoring, n_jobs=n_jobs)
        gridsearch.fit(train_input, train_target)
    
    return gridsearch

In [33]:
kfold = KFold(n_splits=10, shuffle=True, random_state=1234)
# cv = kfold.split(X_train)

In [34]:
results = []
# for i in range(len(models)):
for i in range(4):
    model = models[i]
    param = params[i]
    result = gridsearch_cv_for_regression(model=model, param=param, kfold=kfold, train_input=X_train, train_target=Y_train)
    result.best_score_
    results.append(result)

[2017-06-27 13:59:04.674122] Start parameter search for model 'Ridge'
[2017-06-27 13:59:08.187465] Finish parameter search for model 'Ridge' (time: 3 seconds)

[2017-06-27 13:59:08.187966] Start parameter search for model 'Lasso'
[2017-06-27 13:59:13.268469] Finish parameter search for model 'Lasso' (time: 5 seconds)

[2017-06-27 13:59:13.268469] Start parameter search for model 'ElasticNet'
[2017-06-27 13:59:19.944724] Finish parameter search for model 'ElasticNet' (time: 6 seconds)

[2017-06-27 13:59:19.945225] Start parameter search for model 'HuberReg'
[2017-06-27 13:59:24.955048] Finish parameter search for model 'HuberReg' (time: 5 seconds)

## 3.3. Test models

In [54]:
for i in range(len(results)):
    Y_test_hat = results[i].predict(X_test)
    rmse = np.sqrt(metrics.mean_squared_error(Y_test, Y_test_hat))
    r2 = metrics.r2_score(Y_test, Y_test_hat)
    print("[%s] RMSE: %.4f // R-square: %.4f" % (models[i][0], rmse, r2))

[Ridge] RMSE: 139.3860 // R-square: 0.3911
[Lasso] RMSE: 139.3325 // R-square: 0.3915
[ElasticNet] RMSE: 139.4398 // R-square: 0.3906
[HuberReg] RMSE: 151.4420 // R-square: 0.2812

## 3.4. Feature engineering

### 3.4.1. Polynomial features

In [70]:
from sklearn.preprocessing import PolynomialFeatures

In [71]:
poly = PolynomialFeatures(degree=2)
X_trans = poly.fit_transform(X)

In [72]:
print("Shape of the original data: ", X.shape)
print("Shape of the transformed data: ", X_trans.shape)

Shape of the original data:  (10886, 13)
Shape of the transformed data:  (10886, 105)

In [74]:
# Divide data into training set and test set
X_train, X_test, Y_train, Y_test = train_test_split(X_trans, Y, test_size=0.3, random_state=1234)

In [75]:
# Grid search
kfold = KFold(n_splits=10, shuffle=True, random_state=1234)

results = []
# for i in range(len(models)):
for i in range(4):
    model = models[i]
    param = params[i]
    result = gridsearch_cv_for_regression(model=model, param=param, kfold=kfold, train_input=X_train, train_target=Y_train)
    result.best_score_
    results.append(result)

[2017-06-27 14:49:58.867887] Start parameter search for model 'Ridge'
[2017-06-27 14:50:06.316868] Finish parameter search for model 'Ridge' (time: 7 seconds)

[2017-06-27 14:50:06.317871] Start parameter search for model 'Lasso'

C:\Users\SNUH\Miniconda3\envs\ml\lib\site-packages\sklearn\linear_model\coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)

[2017-06-27 14:51:22.274872] Finish parameter search for model 'Lasso' (time: 75 seconds)

[2017-06-27 14:51:22.274872] Start parameter search for model 'ElasticNet'

C:\Users\SNUH\Miniconda3\envs\ml\lib\site-packages\sklearn\linear_model\coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)

[2017-06-27 14:54:45.564503] Finish parameter search for model 'ElasticNet' (time: 203 seconds)

[2017-06-27 14:54:45.565506] Start parameter search for model 'HuberReg'
[2017-06-27 14:55:03.502209] Finish parameter search for model 'HuberReg' (time: 17 seconds)

In [76]:
# Test models
for i in range(len(results)):
    Y_test_hat = results[i].predict(X_test)
    rmse = np.sqrt(metrics.mean_squared_error(Y_test, Y_test_hat))
    r2 = metrics.r2_score(Y_test, Y_test_hat)
    print("[%s] RMSE: %.4f // R-square: %.4f" % (models[i][0], rmse, r2))

[Ridge] RMSE: 119.4605 // R-square: 0.5527
[Lasso] RMSE: 120.5183 // R-square: 0.5448
[ElasticNet] RMSE: 120.6912 // R-square: 0.5435
[HuberReg] RMSE: 151.1236 // R-square: 0.2842

### 3.4.2. Principal component analysis (PCA)

In [92]:
from sklearn.decomposition import PCA

In [93]:
pca = PCA(n_components='mle', svd_solver='full')

In [94]:
X_pca = pca.fit_transform(X.values)

In [95]:
X_pca.shape

(10886, 12)

In [96]:
print("Shape of the original data: ", X.shape)
print("Shape of the transformed data by PCA: ", X_pca.shape)

Shape of the original data:  (10886, 13)
Shape of the transformed data by PCA:  (10886, 12)

In [100]:
# Divide data into training set and test set
X_train, X_test, Y_train, Y_test = train_test_split(X_pca, Y, test_size=0.3, random_state=1234)

In [101]:
# Grid search
kfold = KFold(n_splits=10, shuffle=True, random_state=1234)

results = []
# for i in range(len(models)):
for i in range(4):
    model = models[i]
    param = params[i]
    result = gridsearch_cv_for_regression(model=model, param=param, kfold=kfold, train_input=X_train, train_target=Y_train)
    result.best_score_
    results.append(result)

[2017-06-27 15:07:00.694708] Start parameter search for model 'Ridge'
[2017-06-27 15:07:03.949687] Finish parameter search for model 'Ridge' (time: 3 seconds)

[2017-06-27 15:07:03.949687] Start parameter search for model 'Lasso'
[2017-06-27 15:07:07.092044] Finish parameter search for model 'Lasso' (time: 3 seconds)

[2017-06-27 15:07:07.092044] Start parameter search for model 'ElasticNet'
[2017-06-27 15:07:10.594358] Finish parameter search for model 'ElasticNet' (time: 3 seconds)

[2017-06-27 15:07:10.595361] Start parameter search for model 'HuberReg'
[2017-06-27 15:07:15.746058] Finish parameter search for model 'HuberReg' (time: 5 seconds)

In [102]:
# Test models
for i in range(len(results)):
    Y_test_hat = results[i].predict(X_test)
    rmse = np.sqrt(metrics.mean_squared_error(Y_test, Y_test_hat))
    r2 = metrics.r2_score(Y_test, Y_test_hat)
    print("[%s] RMSE: %.4f // R-square: %.4f" % (models[i][0], rmse, r2))

[Ridge] RMSE: 139.4304 // R-square: 0.3907
[Lasso] RMSE: 139.4135 // R-square: 0.3908
[ElasticNet] RMSE: 139.4459 // R-square: 0.3905
[HuberReg] RMSE: 143.3842 // R-square: 0.3556